### ISSUE TITLE
Не работает функция "Перехват на ответственного" в Битрикс24

### ISSUE THREAD

**Issue by atar90** [mikopbx/ModuleBitrix24Integration#12]
В битриксе 2 номера: 204 и 207.
Входящая маршрутизация на АТС через провайдера Мегафон на 204 номер.
По компании "ИП Мжельская" ответственный - Fedorov, номер 207 под ним был залогинен битрикс с atar@miko.ru.
При входящем звонке звонок не ушел на 207, а пошел  на 204 - по правилу входящей маршрутизации.

АТС MikoPBX версии **2021.2.194.**
Модуль АТС "Интеграция с CRM Bitrix24", **версия 1.94.**
**172.16.32.76**

Битрикс24 триальный на 30 дней    
для входа        **b24-rmp.bitrix24.ru**

**Comment by boffart** [comment]
Проверил на свежем портале и актуальной версии модуля интеграции с b24
Все корректно отработало.
