### ISSUE TITLE
Добавить вариант работы через REST API, чтобы не надо было покупать подписку Bitrix

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/ModuleBitrix24Integration#13]
Например в списке стран, добавить еще один вариант через RestAPI, при его выборе появляются необходимые поля для указания ключей авторизации. + обновить инструкцию, добавить вариант как было раньше.
Щас многие клиенты не ставят модуль, т.к. дополнительно нему надо покупать подписку за более чем 30 тысяч в год

**Comment by boffart** [comment]
Дополнил документацию
https://wiki.mikopbx.com/modules:b24crm:bitrixapp#regiona_net_v_spiske
