### ISSUE TITLE
+ в исходящем звонке

### ISSUE THREAD

**Issue by YanchikAmb** [mikopbx/ModuleBitrix24Integration#2]
Добрый день, коллеги! В новой версии в модуле интеграции с битриксом есть косяк. звонки из битрикса отправляются в формате +375.... или +7..... Атс на это даже не реагирует. В предыдущих версиях работало. При отправке звонка через 00 или без плюса звонок проходит нормально. Проблема в том, что все входящие звонки в битриксе автоматом подтягиваются с + и соответственно номера +375445557090 и 00375445557090 и 375445557090 битрикс считает разными лидами, что очень неудобно. Можно с этим что-то сделать?

**Comment by boffart** [comment]
Это не баг, а фича. Раньше + заменялся на 00, теперь это отключили. Большинство провайдеров поддерживают набор через "+". 
Вот инструкции
https://wiki.mikopbx.com/faq:outbound-routes:plus_replace
Вам нужно добавить что то вроде

```
[outgoing](+)
exten => _+X!,1,Set(ADDPLUS=00);
    same => n,Goto(${CONTEXT},${EXTEN:1},1);
```

**Comment by YanchikAmb** [comment]
звонок через + с АТС проходит, он не проходит именно в модуле интеграции. В предыдущих версиях работало через +

**Comment by boffart** [comment]
инструкции выше пробовали?

**Comment by YanchikAmb** [comment]
пробовал - результат такой же

**Comment by boffart** [comment]
Приложите лог звонка
[Инструкция для получения логов в Putty](https://wiki.mikopbx.com/faq:putty_log)

**Comment by boffart** [comment]
Воспроизвел, поправил.
