### ISSUE TITLE
Доработать ссылку на очередь для "обратного звонка"

### ISSUE THREAD

**Issue by azim22** [mikopbx/ModuleBitrix24Integration#22]
Добавить в модуль пункт выбора очереди для обратных звонков. Так как она ссылается на очередь "по умолчанию". Или дать возможность выбора одного сотрудника, кто будет обрабатывать обратные звонки.

**Comment by boffart** [comment]
С очердью вариант наиболее правильный. 
В очереди есть возможность настроить callerid(name), на телефоне можно отобразить надпись "callback <74952293042>" при получении callback. Сотрудник будет понимать ,что это обратный звонок. 

Сделано, доступно в develop ветке, как протестируем перенесем в релиз.
