### ISSUE TITLE
Не работает обратный звонок с сайта. 

### ISSUE THREAD

**Issue by boffart** [mikopbx/ModuleBitrix24Integration#30]
https://qa.mikopbx.ru/12301/проблемы-с-обратным-звонокм-с-сайта

**Comment by Div2303** [comment]
опять сломалось?

**Comment by boffart** [comment]
функционал не менялся. если только со стороны b24 какие то изменения
вот обсуждение на эту тему
https://qa.mikopbx.ru/12301/проблемы-с-обратным-звонокм-с-сайта?show=13094#c13094
