### ISSUE TITLE
Доработка по переводу вызовов

### ISSUE THREAD

**Issue by Abrasha94** [mikopbx/ModuleBitrix24Integration#33]
стоит создание лида после окончания разговора, но опять же в случае перевода вызова (тут не важно на группу или пользователя) отвественный становится первым кто поднял трубку, а не последний кто разговаривал/положил. Можно ли это как исправить? иначе смысл той настройки когда создавать лид

**Comment by boffart** [comment]
Поправил, лид будет направлен на того, кто последний поговорил с клиентом.
