### ISSUE TITLE
Исходящий пропущенный, не корректный ответственный

### ISSUE THREAD

**Issue by boffart** [mikopbx/ModuleBitrix24Integration#36]
если менеджер не дозвонился то формируется пропущенный звонок и вешается на этого ответственного который в совершенно другом отделе

https://qa.mikopbx.ru/12323/интеграция-bitrix24-позволяет-bitrix24-входящем-отображать?show=12766#c12766

**Comment by Div2303** [comment]
Супер спасибо ждем)
