### ISSUE TITLE
Создавать лид только у того сотрудника, который принял вызов

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/ModuleBitrix24Integration#4]
При звонке на группу у всех из группы появляются Дела  (пропущенные звонки , и у одного оператора - принят и запись разговора ).  ЛИД распределяется по группе рандомно, даже не тому оператору который поднял трубку.

По настройкам  телефонии в Б24  - поставили  параметр : Запускать бизнес-процесс создания нового лида  - В момент окончания звонка. 

Как я понимаю лид должен создаваться только у того, кто поднял трубку. У остальных не должно создаваться дел и Лидов.

**Comment by boffart** [comment]
Поправил. 
Нашел баг в WorkerCdr (в core).
