### ISSUE TITLE
Дата последней коммуникации

### ISSUE THREAD

**Issue by Abrasha94** [mikopbx/ModuleBitrix24Integration#44]
Иногда бывает, что в карточке контакта такая беда
![image (662)](https://user-images.githubusercontent.com/85700762/203800871-9d66e2fa-ea75-401c-b124-d5cfc152f826.png)
дата последней коммуникации не изменяется, хотя есть последующие звонки

**Comment by Abrasha94** [comment]
![image (663)](https://user-images.githubusercontent.com/85700762/203906818-ce58fa63-5796-46bc-a702-bda5165d99d6.png)

**Comment by boffart** [comment]
Я не вижу возможности через API управлять значением в поле "Дата последней коммуникации". 
Обратитесь в ТП Bitrix24.
