### ISSUE TITLE
Функция перехват на ответственного

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/ModuleBitrix24Integration#5]
Добавить в модуль резервный номер, как и в модуле умной маршрутизации направление по-умолчанию, если ответственный не ответил за указанное (15 секунд по-умолчанию) время.

Если функция включена в модуле, то при входящем звонке узнать у CRM кто отверженный, и попытаться на него отправить вызов, если номер недоступен или не ответили за настроенное в форме модуля время - вызов идет на маршрут по умолчанию или в идеале на маршрут по умолчанию для станции... Тогда и настроек меньше, и логика не ломается.

**Comment by boffart** [comment]
Готово.
