### ISSUE TITLE
Поддержка виджета обратного звонка из Bitrix24

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/ModuleBitrix24Integration#6]
Можем мы сделать так, чтобы стандартный виджет  обратного звонка из Bitrix24 звонил через нашу АТС, как здесь указано?

https://help.megapbx.ru/callback_bitrix

Для этого надо только на стороне портала делать настройки или в модуле тоже надо дорабатывать?

**Comment by boffart** [comment]
У нас задействована функция обратного звонка с сайта, только пока входящий маршрут задействуется дефолтный.

**Comment by jorikfon** [comment]
Ну наверное это норм, попробую включить на нашем сайте, напишу результат.

**Comment by boffart** [comment]
Проверил. Улучшил работу, поправил ошибку с формированием dialplan.
