### ISSUE TITLE
Не подтягивается номер телефона пропущенного звонка в лид Битрикс24.

### ISSUE THREAD

**Issue by planeta0** [mikopbx/ModuleBitrix24Integration#74]
Здравствуйте, я писал Вам в Телеграм. Отправляю Вам логи с трех звонков один в нерабочие время второй и третий не был приняты операторами
[Downloads.zip](https://github.com/mikopbx/ModuleBitrix24Integration/files/13681884/Downloads.zip)
![Снимок экрана (127)](https://github.com/mikopbx/ModuleBitrix24Integration/assets/111510283/3a6483a0-3c43-497c-b3bf-200ce25745ba)
.

**Comment by boffart** [comment]
Вы имеете в виду лиды по клиентам "Фатеев..." и "Коростель..."? 
Наше приложение не создает лидов с таким названием, модуль вовсе не управляет наименованием, оно формируется автоматически порталов в формате:

<Номер телефона> - <Направление звонка>
